### ISSUE TITLE
missing component:setsource ?

### ISSUE THREAD

**Issue by ensonic** [flowbased/fbp-protocol#2]
In many places e.g.
https://github.com/noflo/noflo-runtime-base/blob/master/src/protocol/Runtime.coffee#L44-51
I see component:setsource, but it is missing in https://github.com/flowbased/fbp-protocol/blob/master/schema/json/component.json

**Comment by jonnor** [comment]
The capability is `component:setsource`, but the message for sending component source is actually `command: "source", protocol: "component", payload: ....`
